language: node_js
node_js:
  - "13.10"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - yarn install
  - yarn generate:gh-pages

script:
  - yarn lint
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
